import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Digitalesque</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <section className="px-6 py-16 md:px-44">
          <h1 className="max-w-[20ch] mt-[40vh] text-4xl font-black tracking-wide md:text-7xl md:leading-none">
            The Digital <br /> Transformation Agency
          </h1>
        </section>

        <section className="px-4 md:px-36">
          <div className="border-t-2 border-black"></div>
          <div className="mt-6 min-h-[80vh] bg-black flex items-end">
            <div className="px-5 py-14  md:px-8 md:py-24">
              <p className="max-w-[40ch] text-xl text-white font-bold tracking-wide md:text-3xl">
                Our MISSION is to offer bespoke, trusted advanced digital
                solutions to the challenges of individuals, businesses, and
                governments in Africa by transforming systems.
              </p>
            </div>
          </div>
        </section>

        <section className="px-6 pt-32 pb-14 md:px-44">
          <h3 className="text-2xl font-extrabold tracking-wide md:text-4xl md:leading-tight">
            Our blueprint for digital transformation below gives an overview of
            the sequence, checklist, and guides at all levels of the
            organization through the journey ensuring that no area of the
            strategy is left unattended during the period of change:
          </h3>
        </section>

        <section className="px-4 pb-32 md:px-36">
          <div className="mb-6 border-t-2 border-black"></div>

          <div className="md:pl-12 md:ml-auto md:w-1/2">
            <div className="px-2 py-6">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                The Central Bank of Nigeria
              </h4>
              <p className="md:text-lg">
                Set-up of the eNaira New Media Infrastructure. Built
                eNaira.gov.ng and the Web App.
              </p>
            </div>

            <div className="px-2 py-6 border-t-2 border-black">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                Tital Trust Bank
              </h4>
              <p className="md:text-lg">
                Web portal Development and Brand Identity
              </p>
            </div>

            <div className="px-2 py-6 border-t-2 border-black">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                The Securities and Exchange Commission (SEC)
              </h4>
              <p className="md:text-lg">
                Website Redesign and Administrative Portals Development
                (Ongoing)
              </p>
            </div>

            <div className="px-2 py-6 border-t-2 border-black">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                The Infrastructural Corporation (InfraCo)
              </h4>
              <p className="md:text-lg">
                Brand Identity, ICT Infrastructure and Website Development{" "}
              </p>
            </div>

            <div className="px-2 py-6 border-t-2 border-black">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                The Nigeria Incentive-Based Risk Sharing System for Agricultural
                Lending (NIRSAL)
              </h4>
              <p className="md:text-lg">
                ICT Infrastructure and Brand Identity Development.
              </p>
            </div>

            <div className="px-2 py-6 border-t-2 border-black">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                The CBN Center for Economics and Finance (CBN-CENEF)
              </h4>
              <p className="md:text-lg">
                Brand Identity and learning management System Integration
              </p>
            </div>

            <div className="px-2 py-6 border-t-2 border-black">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                The Office of the Chief Economic Adviser to the President
              </h4>
              <p className="md:text-lg">
                ICT Infrastructure and New Media Orchestration for The World
                Economic Forum on Africa
              </p>
            </div>

            <div className="px-2 py-6 border-t-2 border-black">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                The Nigeria Police Force
              </h4>
              <p className="md:text-lg">
                Police Complaint Units’ ICT integration
              </p>
            </div>

            <div className="px-2 py-6 border-t-2 border-black">
              <h4 className="text-xl font-extrabold tracking-wide md:text-3xl">
                The Bayelsa State Government
              </h4>
              <p className="md:text-lg">
                New Media Set up and Website Development for The Bayelsa Jazz
                Festival
              </p>
            </div>
          </div>
        </section>

        <section>
          <div className="px-6 py-10 md:px-44">
            <h3 className="text-xl font-bold tracking-wide md:text-3xl">
              Our Insights
            </h3>
          </div>

          <div className="grid grid-cols-1 md:gap-1 md:grid-cols-4">
            <div className="bg-black min-h-[50vh] text-white">
              <div className="p-6 md:p-8">
                <a href="" className="group hover:text-gray-400">
                  <p className="mb-3 text-xl font-extrabold tracking-wide md:text-3xl group-hover:underline">
                    Tuning into Africa’s digital transformation
                  </p>
                  <span className="text-sm">LEARN MORE</span>
                </a>
              </div>
            </div>

            <div className="bg-black min-h-[50vh] text-white">
              <div className="p-6 md:p-8">
                <a href="" className="group hover:text-gray-400">
                  <p className="mb-3 text-xl font-extrabold tracking-wide md:text-3xl group-hover:underline">
                    Digital transformation in Africa: three lessons from
                    India&#39;s experience
                  </p>
                  <span className="text-sm">LEARN MORE</span>
                </a>
              </div>
            </div>

            <div className="bg-black min-h-[50vh] text-white">
              <div className="p-6 md:p-8">
                <a href="" className="group hover:text-gray-400">
                  <p className="mb-3 text-xl font-extrabold tracking-wide md:text-3xl group-hover:underline">
                    The promises and perils of Africa’s digital revolution
                  </p>
                  <span className="text-sm">LEARN MORE</span>
                </a>
              </div>
            </div>

            <div className="bg-black min-h-[50vh] text-white md:min-h-[70vh]">
              <div className="p-6 md:p-8">
                <a href="" className="group hover:text-gray-400">
                  <p className="mb-3 text-xl font-extrabold tracking-wide md:text-3xl group-hover:underline">
                    Improving Africa’s digital and innovation ecosystems: five
                    ways forward
                  </p>
                  <span className="text-sm">LEARN MORE</span>
                </a>
              </div>
            </div>
          </div>

          <div className="px-6 py-10 text-right md:px-44 md">
            <a href="" className="text-lg underline md:text-xl">
              More Insights
            </a>
          </div>
        </section>

        <section className="px-6 pt-32 pb-14 md:px-44">
          <h3 className="max-w-[40ch] text-2xl font-extrabold tracking-wide md:text-3xl md:leading-tight">
            If you’re interested in working with us and want to find out more
            about the results we’ve achieved, we’d love to hear from you
          </h3>
        </section>

        <section className="px-4 pb-16 md:px-36">
          <div className="border-t-2 border-black"></div>
          <div className="mt-6 w-2/3 ml-auto px-2 py-8 md:w-2/5 md:p-8">
            <h4 className="max-w-[40ch] text-xl font-bold tracking-wide md:text-2xl">
              Can we do business?
            </h4>
            <a
              href=""
              className="text-lg underline md:text-xl hover:text-gray-500"
            >
              Click this link to give us a shout.
            </a>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
